import localFont from 'next/font/local'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: [
    {
      path: '../public/Outfit-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/Outfit-Regular.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={myFont.className}>
      <body>
        <div className="flex h-full w-full flex-col">
          <div className="relative h-full w-full flex-1 transition-colors z-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
